# Generated by Django 3.1.5 on 2021-01-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='grocery_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.IntegerField(default=True)),
                ('location', models.CharField(choices=[('Pantry', 'Pantry'), ('Fridge', 'Refrigerator'), ('Freezer', 'Freezer')], max_length=7)),
                ('taxable', models.BooleanField(default=True)),
            ],
        ),
    ]
