# Generated by Django 3.1.5 on 2021-01-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery_item',
            name='status',
            field=models.CharField(choices=[('Sale', 'On sale'), ('Full', 'Full price')], default='Full', max_length=4),
        ),
    ]
