# Generated by Django 3.1.5 on 2021-01-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_auto_20210108_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
    ]
